sudo: required
services:
    - docker

before_install:
    - docker build -t mikeonline/multi-docker-react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run mikeonline/multi-docker-react-test npm test -- --watchAll=false

after_success:
    - docker build -t mikeonline/multi-docker-client  ./client
    - docker build -t mikeonline/multi-docker-server ./server
    - docker build -t mikeonline/multi-docker-nginx ./nginx
    - docker build -t mikeonline/multi-docker-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push mikeonline/multi-docker-client
    - docker push mikeonline/multi-docker-server
    - docker push mikeonline/multi-docker-nginx
    - docker push mikeonline/multi-docker-worker
